
              .global        TWO
              .global        HALF
              .global        NONE

              .text

              .align         32
TWO:          .double        2.0
              .double        2.0
              .double        2.0
              .double        2.0
HALF:         .double        0.5
              .double        0.5
              .double        0.5
              .double        0.5
NONE:         .double        -1.0
              .double        -1.0
              .double        -1.0
              .double        -1.0
